# Generated by Django 4.0.5 on 2022-10-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0010_student_surname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="age",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
